import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

export const GENERATED_NOTICE =
  "<!-- Generated by `pnpm reference:generate`. Do not edit; `pnpm reference:check` compares this file with its sources. -->";

/** The shared "which release is this" section on every reference page. */
export function releaseSection(packageVersion?: string): string {
  const packageNote =
    packageVersion === undefined
      ? ""
      : ` The package manifest version is \`${packageVersion}\`.`;
  return [
    "## Which release this describes",
    "",
    "This page documents the code on the `main` branch. The source stamp is not an npm release or a development snapshot. <ReleaseStamp />",
    "",
    `Install an exact npm version or use a version-pinned npm CDN module. The npm \`alpha\` tag moves between reviewed prereleases. It is not a main-build snapshot. Check the [GitHub Releases](https://github.com/Sefaria/sefaria-frontend-toolkit/releases) for the source and notes of your installed version. Older pinned releases keep their own behavior and can lack APIs added since.${packageNote} [Install and status](/help/install-and-status.md) lists package commands and jsDelivr/UNPKG files.`,
  ].join("\n");
}

export async function renderPage({
  title,
  heading,
  description,
  body,
}: {
  readonly title: string;
  readonly heading: string;
  readonly description: string;
  readonly body: string;
}): Promise<string> {
  const page = [
    "---",
    `title: ${JSON.stringify(title)}`,
    `description: ${JSON.stringify(description)}`,
    "---",
    "",
    GENERATED_NOTICE,
    "",
    "<script setup>",
    'import ReleaseStamp from "./ReleaseStamp.vue";',
    "</script>",
    "",
    "> Created/edited by GitHub Copilot; pending human review.",
    "",
    `# ${heading}`,
    "",
    body,
    "",
  ].join("\n");
  const filepath = fileURLToPath(
    new URL("../../docs/reference/page.md", import.meta.url),
  );
  return format(page, { ...(await resolveConfig(filepath)), filepath });
}
