import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

export const GENERATED_NOTICE =
  "<!-- Generated by `pnpm reference:generate`. Do not edit; `pnpm reference:check` compares this file with its sources. -->";

/** The shared "which release is this" section on every reference page. */
export function releaseSection(packageVersion?: string): string {
  const packageNote =
    packageVersion === undefined
      ? ""
      : ` The package manifest version is \`${packageVersion}\`.`;
  return [
    "## Which release this describes",
    "",
    "This page documents the code on the `main` branch, which `alpha` builds are published from. <ReleaseStamp />",
    "",
    `The \`alpha\` script-tag address serves the newest script release that is still active. Compare the stamp above with the version in the [script-tag versions index](https://arithmomaniac.github.io/sefaria-frontend-toolkit/cdn/index.html). Older pinned script-tag versions keep their own behavior for as long as the host keeps them available. An older pin can also lack attributes added since.${packageNote}`,
  ].join("\n");
}

export async function renderPage({
  title,
  heading,
  description,
  body,
}: {
  readonly title: string;
  readonly heading: string;
  readonly description: string;
  readonly body: string;
}): Promise<string> {
  const page = [
    "---",
    `title: ${JSON.stringify(title)}`,
    `description: ${JSON.stringify(description)}`,
    "---",
    "",
    GENERATED_NOTICE,
    "",
    "<script setup>",
    'import ReleaseStamp from "./ReleaseStamp.vue";',
    "</script>",
    "",
    "> Created/edited by GitHub Copilot; pending human review.",
    "",
    `# ${heading}`,
    "",
    body,
    "",
  ].join("\n");
  const filepath = fileURLToPath(
    new URL("../../docs/reference/page.md", import.meta.url),
  );
  return format(page, { ...(await resolveConfig(filepath)), filepath });
}
